### PR TITLE
Force Resource limits to Strings

### LINKED ISSUE #121: Cannot start instance with error: Go struct field EnvVar.spec.template.spec.containers.env.value of type string
### Current Behavior

Cannot start instance with error:
```json
{"statusCode":400,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment in version \"v1\" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string","reason":"BadRequest","code":400}
```

K8s Deployment ENV
```json
"env": [
              {
                "name": "TZ",
                "value": "Europe/London"
              },
              {
                "name": "FORGE_CLIENT_ID",
                "value": "ffp_1gkCsIqdZKFW8AF-5-1n0BgtFdvnktW64cKwzR7tJ94"
              },
              {
                "name": "FORGE_CLIENT_SECRET",
                "value": "GjML-nMDCIRxvFEN3a4fnjG4w3imSHzpbs2xW56hURRtApOBTxYrreswDd0RpJLs"
              },
              {
                "name": "FORGE_URL",
                "value": "http://forge.flowforge"
              },
              {
                "name": "BASE_URL",
                "value": "https://precious-purple-sandpiper-7561.forge.k8s.xxx"
              },
              {
                "name": "FORGE_TEAM_ID",
                "value": "34qaN4xX5v"
              },
              {
                "name": "FORGE_PROJECT_ID",
                "value": "8dcb5b43-06fe-4541-ae3f-2695027c9ec0"
              },
              {
                "name": "FORGE_PROJECT_TOKEN",
                "value": "fft_R0qEj6XaI-UN4uPjJNhu2xR8xKtNgvWPfDaUFnOzOnE"
              },
              {
                "name": "FORGE_NR_NO_TCP_IN",
                "value": "true"
              },
              {
                "name": "FORGE_NR_NO_UDP_IN",
                "value": "true"
              },
              {
                "name": "FORGE_BROKER_URL",
                "value": "mqtt://flowforge-broker.flowforge:1883"
              },
              {
                "name": "FORGE_BROKER_USERNAME",
                "value": "project:34qaN4xX5v:8dcb5b43-06fe-4541-ae3f-2695027c9ec0"
              },
              {
                "name": "FORGE_BROKER_PASSWORD",
                "value": "ffbp_cU0eStkmHZnT_1TliMcMmASelIn8ZCcscXflCnLZQMQ"
              },
              {
                "name": "FORGE_LICENSE_TYPE",
                "value": "ee"
              },
              {
                "name": "FORGE_MEMORY_LIMIT",
                "value": 256
              },
              {
                "name": "FORGE_CPU_LIMIT",
                "value": 10
              },
              {
                "name": "FORGE_NR_SECRET",
                "value": "54b4a8c405a487e67d83121a58440f26ce4bddb3ddd1ab10127c31bce0b0c494"
              }
            ],
```

Maybe issue related to FORGE_MEMORY_LIMIT and FORGE_CPU_LIMIT with value is int instead of string

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

- FlowFuse version: v1.12.5
- Node.js version: v16.20.2
- npm version:
- Platform/OS: k8s
- Browser:

### PR DESCRIPTION
**Pull request by hardillb**
fixes #121

## Description

Values for resource limits are added as numbers but later versions of K8s require all env vars to be strings.

## Related Issue(s)

#121 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: kubernetes.js [hunk 1]
```diff
@@ -271,10 +271,10 @@ const createDeployment = async (project, options) => {
         localPod.spec.containers[0].env.push({ name: 'FORGE_LICENSE_TYPE', value: 'ee' })
     }
     if (stack.memory) {
-        localPod.spec.containers[0].env.push({ name: 'FORGE_MEMORY_LIMIT', value: stack.memory })
+        localPod.spec.containers[0].env.push({ name: 'FORGE_MEMORY_LIMIT', value: stack.memory.toString() })
```
Comment (Pezmc) [inline kubernetes.js:274]: Does `stack.memory` always return an object (i.e. will toString()` always exist on it?)

**Review by Pezmc — APPROVED** [review]
One sanity check, otherwise 👍

File: kubernetes.js (hunk 1 above)
Comment (hardillb) [reply kubernetes.js:274]: It should always contain a number, but I suppose we could replace this with 

```suggestion
        localPod.spec.containers[0].env.push({ name: 'FORGE_MEMORY_LIMIT', value: `${stack.memory}` })
```

Comment (Pezmc) [reply kubernetes.js:274]: Yep I think that's slightly safer (also a number is a type of object)

File: kubernetes.js [hunk 2]
```diff
@@ -271,10 +271,10 @@ const createDeployment = async (project, options) => {
         localPod.spec.containers[0].env.push({ name: 'FORGE_LICENSE_TYPE', value: 'ee' })
     }
     if (stack.memory) {
-        localPod.spec.containers[0].env.push({ name: 'FORGE_MEMORY_LIMIT', value: stack.memory })
+        localPod.spec.containers[0].env.push({ name: 'FORGE_MEMORY_LIMIT', value: `${stack.memory}` })
     }
     if (stack.cpu) {
-        localPod.spec.containers[0].env.push({ name: 'FORGE_CPU_LIMIT', value: stack.cpu })
+        localPod.spec.containers[0].env.push({ name: 'FORGE_CPU_LIMIT', value: stack.cpu.toString() })
```
Comment (Pezmc) [inline kubernetes.js:277]:
```suggestion
        localPod.spec.containers[0].env.push({ name: 'FORGE_CPU_LIMIT', value: `${stack.cpu}` })
```
